"""API test helpers for Vedro scenarios.

Provides test utilities for creating test apps, JWT tokens, and seeding test data
for API endpoint testing.

Example:
    >>> from scenarios.contexts.api_helpers import created_test_app, created_test_jwt
    >>>
    >>> class Scenario(vedro.Scenario):
    ...     subject = "get api history"
    ...
    ...     def given_test_app(self):
    ...         self.app, self.state = created_test_app()
    ...         self.client = TestClient(self.app)
    ...         self.token = created_test_jwt(self.state.settings)
    ...
    ...     def when_request_sent(self):
    ...         self.response = self.client.get(
    ...             "/api/history",
    ...             headers={"Authorization": f"Bearer {self.token}"}
    ...         )
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any
from unittest.mock import AsyncMock, MagicMock

import jwt
import vedro
from d42 import fake

from gitlab_queue.api.websocket import WebSocketManager
from gitlab_queue.config import Secret
from gitlab_queue.db.database import DatabaseStatus
from gitlab_queue.health import ApplicationHealth, ComponentStatus, GitLabHealth
from gitlab_queue.models.queue_item import QueueItem
from gitlab_queue.utils.circuit_breaker import CircuitBreaker, CircuitState
from gitlab_queue.webhooks.router import WebhookAppState, create_webhook_app
from scenarios.contexts.sqlite_client import initialized_test_database
from scenarios.library import Labels, QueueState
from scenarios.schemas import (
    AuthorSchema,
    JWTSecretSchema,
    QueueItemSchema,
    WebhookSecretSchema,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator

    from fastapi import FastAPI

    from gitlab_queue.db.database import Database


# =============================================================================
# Mock Factories
# =============================================================================


_GENERATE = object()  # Sentinel for "generate this value"


def created_mock_settings(
    *,
    jwt_secret: str | None = None,
    jwt_expiration_hours: int = 24,
    gitlab_url: str = "https://gitlab.example.com",
    gitlab_project_id: int | None = None,
    queue_label: str = Labels.MERGE_QUEUE,
    hotfix_label: str = Labels.HOTFIX,
    oauth_client_id: str | None | object = _GENERATE,
    oauth_client_secret: str | None | object = _GENERATE,
    oauth_redirect_uri: str | None = "http://localhost:8080/auth/callback",
    webhook_secret: str | None = None,
) -> MagicMock:
    """Create mock settings for testing.

    Uses d42 schemas to generate realistic random data for secret values.

    Args:
        jwt_secret: JWT signing secret (generated if not provided).
        jwt_expiration_hours: JWT token expiration in hours.
        gitlab_url: GitLab instance URL.
        gitlab_project_id: GitLab project ID (generated if not provided).
        queue_label: Label for merge queue.
        hotfix_label: Label for hotfix priority.
        oauth_client_id: OAuth client ID (generated by default, pass None to disable).
        oauth_client_secret: OAuth client secret (generated by default, pass None to disable).
        oauth_redirect_uri: OAuth redirect URI.
        webhook_secret: Webhook validation secret (generated if not provided).

    Returns:
        MagicMock: Mock settings object with all required attributes configured.
    """
    # Generate secrets using d42 schemas
    actual_jwt_secret = jwt_secret if jwt_secret is not None else fake(JWTSecretSchema)
    actual_webhook_secret = webhook_secret if webhook_secret is not None else fake(WebhookSecretSchema)
    actual_project_id = gitlab_project_id if gitlab_project_id is not None else fake(AuthorSchema)["id"]

    # Handle oauth settings - allow explicit None
    actual_oauth_client_id: str | None = (
        fake(WebhookSecretSchema) if oauth_client_id is _GENERATE else oauth_client_id  # type: ignore[assignment]
    )
    actual_oauth_client_secret: str | None = (
        fake(WebhookSecretSchema) if oauth_client_secret is _GENERATE else oauth_client_secret  # type: ignore[assignment]
    )

    settings = MagicMock()
    settings.jwt_secret = Secret(actual_jwt_secret)
    settings.jwt_expiration_hours = jwt_expiration_hours
    settings.gitlab_url = gitlab_url
    settings.gitlab_project_id = actual_project_id
    settings.gitlab_token = Secret(fake(WebhookSecretSchema))
    settings.queue_label = queue_label
    settings.hotfix_label = hotfix_label
    settings.webhook_host = "0.0.0.0"
    settings.webhook_port = 8080
    settings.cors_origins = ["http://localhost:5173"]
    settings.dashboard_enabled = True
    settings.oauth_client_id = actual_oauth_client_id
    settings.oauth_client_secret = Secret(actual_oauth_client_secret) if actual_oauth_client_secret else None
    settings.oauth_redirect_uri = oauth_redirect_uri
    settings.webhook_secret = Secret(actual_webhook_secret)
    assert settings.jwt_secret is not None, "Settings should have jwt_secret"
    return settings


# Alias for backward compatibility
create_mock_settings = created_mock_settings


def created_mock_database(*, connected: bool = True, wal_mode: bool = True) -> MagicMock:
    """Create mock database with configurable health status.

    Args:
        connected: Whether database is connected.
        wal_mode: Whether WAL mode is enabled.

    Returns:
        MagicMock: Mock database object with health_check configured.
    """
    db = MagicMock()
    db.health_check = AsyncMock(
        return_value=DatabaseStatus(
            connected=connected,
            wal_mode_enabled=wal_mode,
            foreign_keys_enabled=True,
            database_path="sqlite+aiosqlite:///:memory:",
            error=None if connected else "Connection failed",
        )
    )
    assert db.health_check is not None, "Mock database should have health_check"
    return db


# Alias for backward compatibility
create_mock_database = created_mock_database


def created_mock_circuit_breaker(state: CircuitState = CircuitState.CLOSED) -> MagicMock:
    """Create mock circuit breaker with configurable state.

    Args:
        state: Circuit breaker state.

    Returns:
        MagicMock: Mock circuit breaker object.
    """
    cb = MagicMock(spec=CircuitBreaker)
    cb.state = state
    cb.failure_count = 0 if state == CircuitState.CLOSED else 5
    cb.failure_threshold = 5
    cb.half_open_timeout = 30.0
    cb._time_until_half_open = MagicMock(return_value=None if state != CircuitState.OPEN else 25.0)
    return cb


# Alias for backward compatibility
create_mock_circuit_breaker = created_mock_circuit_breaker


def created_mock_gitlab_client(*, circuit_state: CircuitState = CircuitState.CLOSED) -> MagicMock:
    """Create mock GitLab client with circuit breaker.

    Args:
        circuit_state: Circuit breaker state.

    Returns:
        MagicMock: Mock GitLab client with circuit_breaker and rate_limit_state configured.
    """
    client = MagicMock()
    client.circuit_breaker = created_mock_circuit_breaker(circuit_state)
    client.rate_limit_state = MagicMock()
    client.rate_limit_state.limit = 2000
    client.rate_limit_state.remaining = 1900
    client.rate_limit_state.usage_ratio = 0.05
    client.rate_limit_state.seconds_until_reset = 3600
    assert client.circuit_breaker is not None, "Client should have circuit_breaker"
    return client


# Alias for backward compatibility
create_mock_gitlab_client = created_mock_gitlab_client


def created_mock_queue_manager() -> MagicMock:
    """Create mock queue manager.

    Returns:
        MagicMock: Mock queue manager with async methods configured.
    """
    qm = MagicMock()
    qm.get_active_queue = AsyncMock(return_value=[])
    qm.get_queue_stats = AsyncMock(
        return_value={
            QueueState.QUEUED: 0,
            QueueState.REBASING: 0,
            QueueState.TESTING: 0,
            QueueState.MERGING: 0,
        }
    )
    qm.get_recent_history = AsyncMock(return_value=[])
    qm.get_dashboard_stats = AsyncMock(
        return_value=MagicMock(
            total_in_queue=0,
            stats_window_days=7,
            merged_count=0,
            failed_count=0,
            success_rate=0.0,
            avg_wait_seconds=0,
            avg_processing_seconds=0,
        )
    )
    assert qm.get_active_queue is not None, "Queue manager should have get_active_queue"
    return qm


# Alias for backward compatibility
create_mock_queue_manager = created_mock_queue_manager


def created_mock_notifier() -> MagicMock:
    """Create mock MR notifier.

    Returns:
        MagicMock: Mock notifier.
    """
    return MagicMock()


# Alias for backward compatibility
create_mock_notifier = created_mock_notifier


def created_mock_retry_manager() -> MagicMock:
    """Create mock webhook retry manager.

    Returns:
        MagicMock: Mock retry manager with DLQ methods configured.
    """
    manager = MagicMock()
    manager.get_dlq_entries = AsyncMock(return_value=[])
    manager.get_dlq_stats = AsyncMock(
        return_value=MagicMock(
            total_count=0,
            by_event_type={},
            oldest_entry=None,
        )
    )
    return manager


# Alias for backward compatibility
create_mock_retry_manager = created_mock_retry_manager


def created_mock_health(
    *,
    db_healthy: bool = True,
    gitlab_circuit_state: CircuitState = CircuitState.CLOSED,
) -> ApplicationHealth:
    """Create application health state.

    Args:
        db_healthy: Whether database is healthy.
        gitlab_circuit_state: GitLab circuit breaker state.

    Returns:
        ApplicationHealth: Health state object with all components configured.
    """
    health = ApplicationHealth()
    health.database = ComponentStatus.HEALTHY if db_healthy else ComponentStatus.UNHEALTHY
    health.processor_running = True
    health.webhook_server_running = True

    if gitlab_circuit_state == CircuitState.CLOSED:
        health.gitlab = GitLabHealth(
            status=ComponentStatus.HEALTHY,
            circuit_state="closed",
            failure_count=0,
        )
    elif gitlab_circuit_state == CircuitState.OPEN:
        health.gitlab = GitLabHealth(
            status=ComponentStatus.UNHEALTHY,
            circuit_state="open",
            failure_count=5,
            retry_after_seconds=25.0,
        )
    else:
        health.gitlab = GitLabHealth(
            status=ComponentStatus.DEGRADED,
            circuit_state="half_open",
            failure_count=5,
        )

    assert health.gitlab is not None, "Health should have gitlab status"
    return health


# Alias for backward compatibility
create_mock_health = created_mock_health


# =============================================================================
# JWT Token Helpers
# =============================================================================


def created_test_jwt(
    settings: MagicMock,
    *,
    user_id: int | None = None,
    username: str | None = None,
    name: str | None = None,
    email: str | None = None,
    avatar_url: str | None = None,
    project_id: int | None = None,
    expires_delta: timedelta | None = None,
) -> str:
    """Create a valid JWT token for testing.

    Uses d42 schemas to generate realistic random data for user fields.

    Args:
        settings: Mock settings with jwt_secret.
        user_id: GitLab user ID (generated if not provided).
        username: GitLab username (generated if not provided).
        name: User display name (generated if not provided).
        email: User email (generated if not provided).
        avatar_url: URL to user avatar (generated if not provided).
        project_id: GitLab project ID (defaults to settings.gitlab_project_id).
        expires_delta: Token expiration time (defaults to settings.jwt_expiration_hours).

    Returns:
        str: Encoded JWT token.
    """
    # Generate user data using d42 schema
    author_data = fake(AuthorSchema)

    actual_user_id = user_id if user_id is not None else author_data["id"]
    actual_username = username if username is not None else author_data["username"]
    actual_name = name if name is not None else author_data["name"]
    actual_email = email if email is not None else f"{actual_username}@example.com"
    actual_avatar_url = avatar_url if avatar_url is not None else author_data.get("avatar_url")

    now = datetime.now(UTC)

    if expires_delta is None:
        expires_delta = timedelta(hours=settings.jwt_expiration_hours)

    expire = now + expires_delta

    payload: dict[str, Any] = {
        "sub": str(actual_user_id),
        "username": actual_username,
        "name": actual_name,
        "email": actual_email,
        "avatar_url": actual_avatar_url,
        "project_id": project_id or settings.gitlab_project_id,
        "exp": expire,
        "iat": now,
    }

    token = jwt.encode(
        payload,
        settings.jwt_secret.get_secret_value(),
        algorithm="HS256",
    )
    assert token, "JWT token should be created"
    return token


# Alias for backward compatibility
create_test_jwt = created_test_jwt


def created_expired_jwt(settings: MagicMock, **kwargs: Any) -> str:
    """Create an expired JWT token for testing.

    Args:
        settings: Mock settings with jwt_secret.
        **kwargs: Additional arguments passed to created_test_jwt.

    Returns:
        str: Expired JWT token.
    """
    return created_test_jwt(settings, expires_delta=timedelta(hours=-1), **kwargs)


# Alias for backward compatibility
create_expired_jwt = created_expired_jwt


def created_invalid_jwt() -> str:
    """Create an invalid JWT token for testing.

    Returns:
        str: Invalid JWT token string.
    """
    return "invalid.jwt.token"


# Alias for backward compatibility
create_invalid_jwt = created_invalid_jwt


# =============================================================================
# Test App Factory
# =============================================================================


def created_webhook_state(
    *,
    settings: MagicMock | None = None,
    database: MagicMock | None = None,
    db_healthy: bool = True,
    gitlab_circuit_state: CircuitState = CircuitState.CLOSED,
) -> WebhookAppState:
    """Create WebhookAppState with mocked dependencies.

    Args:
        settings: Optional custom settings mock.
        database: Optional custom database mock.
        db_healthy: Whether database should be healthy.
        gitlab_circuit_state: GitLab circuit breaker state.

    Returns:
        WebhookAppState: Configured app state with all dependencies.
    """
    state = WebhookAppState(
        settings=settings or created_mock_settings(),
        database=database or created_mock_database(connected=db_healthy),
        gitlab_client=created_mock_gitlab_client(circuit_state=gitlab_circuit_state),
        queue_manager=created_mock_queue_manager(),
        notifier=created_mock_notifier(),
        position_notifier=None,
        retry_manager=created_mock_retry_manager(),
        health=created_mock_health(
            db_healthy=db_healthy,
            gitlab_circuit_state=gitlab_circuit_state,
        ),
        websocket_manager=WebSocketManager(),
    )
    assert state.settings is not None, "State should have settings"
    return state


# Alias for backward compatibility
create_webhook_state = created_webhook_state


def created_test_app(
    *,
    settings: MagicMock | None = None,
    database: MagicMock | None = None,
    db_healthy: bool = True,
    gitlab_circuit_state: CircuitState = CircuitState.CLOSED,
) -> tuple[FastAPI, WebhookAppState]:
    """Create a test FastAPI app with mocked dependencies.

    Args:
        settings: Optional custom settings mock.
        database: Optional custom database mock.
        db_healthy: Whether database should be healthy.
        gitlab_circuit_state: GitLab circuit breaker state.

    Returns:
        Tuple of (FastAPI app, WebhookAppState).
    """
    state = created_webhook_state(
        settings=settings,
        database=database,
        db_healthy=db_healthy,
        gitlab_circuit_state=gitlab_circuit_state,
    )
    app = create_webhook_app(state)
    assert app is not None, "App should be created"
    return app, state


# Alias for backward compatibility
create_test_app = created_test_app


@vedro.context
@asynccontextmanager
async def created_test_app_with_db() -> AsyncIterator[tuple[FastAPI, WebhookAppState, Database]]:
    """Create a test FastAPI app with real in-memory database.

    This provides a fully functional app with real database for integration testing.
    Includes guaranteeing assertion that app and database are properly initialized.

    Yields:
        Tuple of (FastAPI app, WebhookAppState, Database).
    """
    async with initialized_test_database() as db:
        settings = created_mock_settings()
        state = WebhookAppState(
            settings=settings,
            database=db,
            gitlab_client=created_mock_gitlab_client(),
            queue_manager=created_mock_queue_manager(),
            notifier=created_mock_notifier(),
            position_notifier=None,
            retry_manager=created_mock_retry_manager(),
            health=created_mock_health(),
            websocket_manager=WebSocketManager(),
        )
        app = create_webhook_app(state)
        assert app is not None, "Test app should be created"
        assert state.database is not None, "State should have database"
        yield app, state, db


# Alias for backward compatibility
create_test_app_with_db = created_test_app_with_db


# =============================================================================
# Test Data Helpers
# =============================================================================


def created_test_queue_item(
    *,
    mr_iid: int | None = None,
    title: str | None = None,
    author_name: str | None = None,
    author_username: str | None = None,
    author_avatar: str | None = None,
    state: str = QueueState.QUEUED,
    is_hotfix: bool = False,
    labels: list[str] | None = None,
    target_branch: str | None = None,
    queued_at: datetime | None = None,
    started_at: datetime | None = None,
    finished_at: datetime | None = None,
    pipeline_id: int | None = None,
    pipeline_status: str | None = None,
    last_error: str | None = None,
    retry_count: int = 0,
) -> QueueItem:
    """Create a test QueueItem.

    Uses d42 schemas to generate realistic random data for required fields.
    Specific fields can be overridden via parameters.

    Args:
        mr_iid: MR internal ID (generated if not provided).
        title: MR title (generated if not provided).
        author_name: Author display name (generated if not provided).
        author_username: Author username (generated if not provided).
        author_avatar: Author avatar URL (generated if not provided).
        state: MR state (queued, rebasing, testing, merging, merged, failed).
        is_hotfix: Whether this is a hotfix.
        labels: MR labels.
        target_branch: Target branch (generated if not provided).
        queued_at: Queue timestamp.
        started_at: Processing start timestamp.
        finished_at: Finish timestamp.
        pipeline_id: Pipeline ID.
        pipeline_status: Pipeline status.
        last_error: Last error message.
        retry_count: Retry count.

    Returns:
        QueueItem: Test queue item with all fields configured.
    """
    # Generate base data using d42 schema
    item_data = fake(QueueItemSchema % {"state": state})

    actual_mr_iid = mr_iid if mr_iid is not None else item_data["mr_iid"]
    actual_title = title if title is not None else item_data["title"]
    actual_author_name = author_name if author_name is not None else item_data["author_name"]
    actual_author_username = author_username if author_username is not None else item_data["author_username"]
    actual_target_branch = target_branch if target_branch is not None else item_data["target_branch"]
    # Use generated avatar_url if available in schema, otherwise use provided or None
    actual_author_avatar = author_avatar if author_avatar is not None else item_data.get("author_avatar")

    item = QueueItem(
        mr_iid=actual_mr_iid,
        title=actual_title,
        author_name=actual_author_name,
        author_username=actual_author_username,
        author_avatar=actual_author_avatar,
        state=state,
        is_hotfix=is_hotfix,
        labels=labels or [Labels.MERGE_QUEUE],
        target_branch=actual_target_branch,
        queued_at=queued_at or datetime.now(UTC),
        started_at=started_at,
        finished_at=finished_at,
        pipeline_id=pipeline_id,
        pipeline_status=pipeline_status,
        last_error=last_error,
        retry_count=retry_count,
    )
    assert item.mr_iid == actual_mr_iid, "Queue item should have correct mr_iid"
    return item


# Alias for backward compatibility
create_test_queue_item = created_test_queue_item


def created_test_history_items(count: int = 5) -> list[QueueItem]:
    """Create a list of test history items.

    Uses d42 schemas to generate realistic random data for each item.

    Args:
        count: Number of items to create.

    Returns:
        List of QueueItem objects representing completed MRs.
    """
    items = []
    # Use only valid QueueState values
    statuses = [QueueState.MERGED, QueueState.FAILED, QueueState.CONFLICT, QueueState.REMOVED]

    for i in range(count):
        status = statuses[i % len(statuses)]
        finished_at = datetime.now(UTC) - timedelta(hours=i)
        queued_at = finished_at - timedelta(minutes=30)
        started_at = queued_at + timedelta(minutes=5)

        # Each item gets unique generated data via d42 schema
        items.append(
            created_test_queue_item(
                state=status,
                queued_at=queued_at,
                started_at=started_at,
                finished_at=finished_at,
                last_error=f"Test error for {status}" if status != QueueState.MERGED else None,
            )
        )

    assert len(items) == count, f"Should create {count} history items"
    return items


# Alias for backward compatibility
create_test_history_items = created_test_history_items


__all__ = [
    # Aliases for backward compatibility
    "create_expired_jwt",
    "create_invalid_jwt",
    "create_mock_circuit_breaker",
    "create_mock_database",
    "create_mock_gitlab_client",
    "create_mock_health",
    "create_mock_notifier",
    "create_mock_queue_manager",
    "create_mock_retry_manager",
    "create_mock_settings",
    "create_test_app",
    "create_test_app_with_db",
    "create_test_history_items",
    "create_test_jwt",
    "create_test_queue_item",
    "create_webhook_state",
    # New names (preferred)
    "created_expired_jwt",
    "created_invalid_jwt",
    "created_mock_circuit_breaker",
    "created_mock_database",
    "created_mock_gitlab_client",
    "created_mock_health",
    "created_mock_notifier",
    "created_mock_queue_manager",
    "created_mock_retry_manager",
    "created_mock_settings",
    "created_test_app",
    "created_test_app_with_db",
    "created_test_history_items",
    "created_test_jwt",
    "created_test_queue_item",
    "created_webhook_state",
]
