"""API test helpers for Vedro scenarios.

Provides test utilities for creating test apps, JWT tokens, and seeding test data
for API endpoint testing.

Example:
    >>> from scenarios.contexts.api_helpers import created_test_app, created_test_jwt
    >>>
    >>> class Scenario(vedro.Scenario):
    ...     subject = "get api history"
    ...
    ...     def given_test_app(self):
    ...         self.app, self.state = created_test_app()
    ...         self.client = TestClient(self.app)
    ...         self.token = created_test_jwt(self.state.settings)
    ...
    ...     def when_request_sent(self):
    ...         self.response = self.client.get(
    ...             "/api/history",
    ...             headers={"Authorization": f"Bearer {self.token}"}
    ...         )
"""

from __future__ import annotations

from contextlib import asynccontextmanager
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any

import jwt
import vedro
from d42 import fake

from gitlab_queue.api.websocket import WebSocketManager
from gitlab_queue.health import ApplicationHealth, ComponentStatus, GitLabHealth
from gitlab_queue.models.queue_item import QueueItem
from gitlab_queue.utils.circuit_breaker import CircuitBreaker, CircuitState
from gitlab_queue.webhooks.router import WebhookAppState, create_webhook_app
from scenarios.contexts.gitlab_client_factory import created_test_settings
from scenarios.contexts.sqlite_client import initialized_test_database
from scenarios.fakes import FakeDatabase, FakeGitLabClient, FakeNotifier, FakeQueueManager, FakeRetryManager
from scenarios.library import Labels, QueueState
from scenarios.schemas import (
    AuthorSchema,
    QueueItemSchema,
    WebhookSecretSchema,
)

if TYPE_CHECKING:
    from collections.abc import AsyncIterator

    from fastapi import FastAPI

    from gitlab_queue.config import Settings
    from gitlab_queue.db.database import Database


# =============================================================================
# Fake Factories
# =============================================================================


_GENERATE = object()  # Sentinel for "generate this value"


def create_mock_settings(
    *,
    jwt_expiration_hours: int = 24,
    gitlab_url: str = "https://gitlab.example.com",
    gitlab_project_id: int | None = None,
    queue_label: str = Labels.MERGE_QUEUE,
    hotfix_label: str = Labels.HOTFIX,
    oauth_client_id: str | None | object = _GENERATE,
    oauth_client_secret: str | None | object = _GENERATE,
    oauth_redirect_uri: str | None = "http://localhost:8080/auth/callback",
    webhook_secret: str | None = None,
) -> Settings:
    """Create test settings for API testing.

    Uses d42 schemas to generate realistic random data for secret values.

    Args:
        jwt_expiration_hours: JWT token expiration in hours.
        gitlab_url: GitLab instance URL.
        gitlab_project_id: GitLab project ID (generated if not provided).
        queue_label: Label for merge queue.
        hotfix_label: Label for hotfix priority.
        oauth_client_id: OAuth client ID (generated by default, pass None to disable).
        oauth_client_secret: OAuth client secret (generated by default, pass None to disable).
        oauth_redirect_uri: OAuth redirect URI.
        webhook_secret: Webhook validation secret (generated if not provided).

    Returns:
        Settings instance configured for API testing.
    """
    actual_webhook_secret = webhook_secret if webhook_secret is not None else fake(WebhookSecretSchema)
    actual_project_id = gitlab_project_id if gitlab_project_id is not None else fake(AuthorSchema)["id"]

    # Handle oauth settings - allow explicit None
    actual_oauth_client_id: str | None = (
        fake(WebhookSecretSchema) if oauth_client_id is _GENERATE else oauth_client_id  # type: ignore[assignment]
    )
    actual_oauth_client_secret: str | None = (
        fake(WebhookSecretSchema) if oauth_client_secret is _GENERATE else oauth_client_secret  # type: ignore[assignment]
    )

    return created_test_settings(
        project_id=actual_project_id,
        gitlab_url=gitlab_url,
        queue_label=queue_label,
        hotfix_label=hotfix_label,
        jwt_expiration_hours=jwt_expiration_hours,
        oauth_client_id=actual_oauth_client_id,
        oauth_client_secret=actual_oauth_client_secret,
        oauth_redirect_uri=oauth_redirect_uri,
        webhook_secret=actual_webhook_secret,
    )


# Alias for backward compatibility
created_mock_settings = create_mock_settings


def created_mock_database(*, connected: bool = True, wal_mode: bool = True) -> FakeDatabase:
    """Create fake database with configurable health status.

    Args:
        connected: Whether database is connected.
        wal_mode: Whether WAL mode is enabled.

    Returns:
        FakeDatabase with health_check configured.
    """
    return FakeDatabase(
        connected=connected,
        wal_mode=wal_mode,
        error=None if connected else "Connection failed",
    )


# Alias for backward compatibility
create_mock_database = created_mock_database


def created_test_circuit_breaker(state: CircuitState = CircuitState.CLOSED) -> CircuitBreaker:
    """Create a real CircuitBreaker with configurable state.

    Args:
        state: Circuit breaker state.

    Returns:
        CircuitBreaker configured for testing.
    """
    cb = CircuitBreaker(failure_threshold=5, half_open_timeout=30.0)
    if state != CircuitState.CLOSED:
        cb._state = state
        cb._failure_count = 5
    return cb


# Keep old names for backward compatibility
created_mock_circuit_breaker = created_test_circuit_breaker
create_mock_circuit_breaker = created_test_circuit_breaker


def created_mock_gitlab_client(*, circuit_state: CircuitState = CircuitState.CLOSED) -> FakeGitLabClient:
    """Create fake GitLab client with circuit breaker.

    Args:
        circuit_state: Circuit breaker state.

    Returns:
        FakeGitLabClient with circuit_breaker and rate_limit_state configured.
    """
    return FakeGitLabClient(
        circuit_breaker=created_test_circuit_breaker(circuit_state),
    )


# Alias for backward compatibility
create_mock_gitlab_client = created_mock_gitlab_client


def created_mock_queue_manager() -> FakeQueueManager:
    """Create fake queue manager.

    Returns:
        FakeQueueManager with default empty state.
    """
    return FakeQueueManager()


# Alias for backward compatibility
create_mock_queue_manager = created_mock_queue_manager


def created_mock_notifier() -> FakeNotifier:
    """Create fake MR notifier.

    Returns:
        FakeNotifier instance.
    """
    return FakeNotifier()


# Alias for backward compatibility
create_mock_notifier = created_mock_notifier


def created_mock_retry_manager() -> FakeRetryManager:
    """Create fake webhook retry manager.

    Returns:
        FakeRetryManager with DLQ methods.
    """
    return FakeRetryManager()


# Alias for backward compatibility
create_mock_retry_manager = created_mock_retry_manager


def created_mock_health(
    *,
    db_healthy: bool = True,
    gitlab_circuit_state: CircuitState = CircuitState.CLOSED,
) -> ApplicationHealth:
    """Create application health state.

    Args:
        db_healthy: Whether database is healthy.
        gitlab_circuit_state: GitLab circuit breaker state.

    Returns:
        ApplicationHealth: Health state object with all components configured.
    """
    health = ApplicationHealth()
    health.database = ComponentStatus.HEALTHY if db_healthy else ComponentStatus.UNHEALTHY
    health.processor_running = True
    health.webhook_server_running = True

    if gitlab_circuit_state == CircuitState.CLOSED:
        health.gitlab = GitLabHealth(
            status=ComponentStatus.HEALTHY,
            circuit_state="closed",
            failure_count=0,
        )
    elif gitlab_circuit_state == CircuitState.OPEN:
        health.gitlab = GitLabHealth(
            status=ComponentStatus.UNHEALTHY,
            circuit_state="open",
            failure_count=5,
            retry_after_seconds=25.0,
        )
    else:
        health.gitlab = GitLabHealth(
            status=ComponentStatus.DEGRADED,
            circuit_state="half_open",
            failure_count=5,
        )

    return health


# Alias for backward compatibility
create_mock_health = created_mock_health


# =============================================================================
# JWT Token Helpers
# =============================================================================


def created_test_jwt(
    settings: Any,
    *,
    user_id: int | None = None,
    username: str | None = None,
    name: str | None = None,
    email: str | None = None,
    avatar_url: str | None = None,
    project_id: int | None = None,
    expires_delta: timedelta | None = None,
) -> str:
    """Create a valid JWT token for testing.

    Uses d42 schemas to generate realistic random data for user fields.

    Args:
        settings: Settings object with jwt_secret.
        user_id: GitLab user ID (generated if not provided).
        username: GitLab username (generated if not provided).
        name: User display name (generated if not provided).
        email: User email (generated if not provided).
        avatar_url: URL to user avatar (generated if not provided).
        project_id: GitLab project ID (defaults to settings.gitlab_project_id).
        expires_delta: Token expiration time (defaults to settings.jwt_expiration_hours).

    Returns:
        str: Encoded JWT token.
    """
    # Generate user data using d42 schema
    author_data = fake(AuthorSchema)

    actual_user_id = user_id if user_id is not None else author_data["id"]
    actual_username = username if username is not None else author_data["username"]
    actual_name = name if name is not None else author_data["name"]
    actual_email = email if email is not None else f"{actual_username}@example.com"
    actual_avatar_url = avatar_url if avatar_url is not None else author_data.get("avatar_url")

    now = datetime.now(UTC)

    if expires_delta is None:
        expires_delta = timedelta(hours=settings.jwt_expiration_hours)

    expire = now + expires_delta

    payload: dict[str, Any] = {
        "sub": str(actual_user_id),
        "username": actual_username,
        "name": actual_name,
        "email": actual_email,
        "avatar_url": actual_avatar_url,
        "project_id": project_id or settings.gitlab_project_id,
        "exp": expire,
        "iat": now,
    }

    token = jwt.encode(
        payload,
        settings.jwt_secret.get_secret_value(),
        algorithm="HS256",
    )
    return token


# Alias for backward compatibility
create_test_jwt = created_test_jwt


def created_expired_jwt(settings: Any, **kwargs: Any) -> str:
    """Create an expired JWT token for testing.

    Args:
        settings: Settings object with jwt_secret.
        **kwargs: Additional arguments passed to created_test_jwt.

    Returns:
        str: Expired JWT token.
    """
    return created_test_jwt(settings, expires_delta=timedelta(hours=-1), **kwargs)


# Alias for backward compatibility
create_expired_jwt = created_expired_jwt


def created_invalid_jwt() -> str:
    """Create an invalid JWT token for testing.

    Returns:
        str: Invalid JWT token string.
    """
    return "invalid.jwt.token"


# Alias for backward compatibility
create_invalid_jwt = created_invalid_jwt


# =============================================================================
# Test App Factory
# =============================================================================


def created_webhook_state(
    *,
    settings: Any | None = None,
    database: Any | None = None,
    db_healthy: bool = True,
    gitlab_circuit_state: CircuitState = CircuitState.CLOSED,
) -> WebhookAppState:
    """Create WebhookAppState with fake dependencies.

    Args:
        settings: Optional custom settings.
        database: Optional custom database.
        db_healthy: Whether database should be healthy.
        gitlab_circuit_state: GitLab circuit breaker state.

    Returns:
        WebhookAppState: Configured app state with all dependencies.
    """
    if settings is None:
        settings = create_mock_settings()
    if database is None:
        database = created_mock_database(connected=db_healthy)

    state = WebhookAppState(
        settings=settings,
        database=database,
        gitlab_client=created_mock_gitlab_client(circuit_state=gitlab_circuit_state),
        queue_manager=created_mock_queue_manager(),
        notifier=created_mock_notifier(),
        position_notifier=None,
        retry_manager=created_mock_retry_manager(),
        health=created_mock_health(
            db_healthy=db_healthy,
            gitlab_circuit_state=gitlab_circuit_state,
        ),
        websocket_manager=WebSocketManager(),
    )
    return state


# Alias for backward compatibility
create_webhook_state = created_webhook_state


def created_test_app(
    *,
    settings: Any | None = None,
    database: Any | None = None,
    db_healthy: bool = True,
    gitlab_circuit_state: CircuitState = CircuitState.CLOSED,
) -> tuple[FastAPI, WebhookAppState]:
    """Create a test FastAPI app with fake dependencies.

    Args:
        settings: Optional custom settings.
        database: Optional custom database.
        db_healthy: Whether database should be healthy.
        gitlab_circuit_state: GitLab circuit breaker state.

    Returns:
        Tuple of (FastAPI app, WebhookAppState).
    """
    state = created_webhook_state(
        settings=settings,
        database=database,
        db_healthy=db_healthy,
        gitlab_circuit_state=gitlab_circuit_state,
    )
    app = create_webhook_app(state)
    return app, state


# Alias for backward compatibility
create_test_app = created_test_app


@vedro.context
@asynccontextmanager
async def created_test_app_with_db() -> AsyncIterator[tuple[FastAPI, WebhookAppState, Database]]:
    """Create a test FastAPI app with real in-memory database.

    This provides a fully functional app with real database for integration testing.

    Yields:
        Tuple of (FastAPI app, WebhookAppState, Database).
    """
    async with initialized_test_database() as db:
        state = created_webhook_state(database=db)
        app = create_webhook_app(state)
        yield app, state, db


# Alias for backward compatibility
create_test_app_with_db = created_test_app_with_db


# =============================================================================
# Test Data Helpers
# =============================================================================


def created_test_queue_item(
    *,
    mr_iid: int | None = None,
    title: str | None = None,
    author_name: str | None = None,
    author_username: str | None = None,
    author_avatar: str | None = None,
    state: str = QueueState.QUEUED,
    is_hotfix: bool = False,
    labels: list[str] | None = None,
    target_branch: str | None = None,
    queued_at: datetime | None = None,
    started_at: datetime | None = None,
    finished_at: datetime | None = None,
    pipeline_id: int | None = None,
    pipeline_status: str | None = None,
    last_error: str | None = None,
    retry_count: int = 0,
) -> QueueItem:
    """Create a test QueueItem.

    Uses d42 schemas to generate realistic random data for required fields.
    Specific fields can be overridden via parameters.

    Args:
        mr_iid: MR internal ID (generated if not provided).
        title: MR title (generated if not provided).
        author_name: Author display name (generated if not provided).
        author_username: Author username (generated if not provided).
        author_avatar: Author avatar URL (generated if not provided).
        state: MR state (queued, rebasing, testing, merging, merged, failed).
        is_hotfix: Whether this is a hotfix.
        labels: MR labels.
        target_branch: Target branch (generated if not provided).
        queued_at: Queue timestamp.
        started_at: Processing start timestamp.
        finished_at: Finish timestamp.
        pipeline_id: Pipeline ID.
        pipeline_status: Pipeline status.
        last_error: Last error message.
        retry_count: Retry count.

    Returns:
        QueueItem: Test queue item with all fields configured.
    """
    # Generate base data using d42 schema
    item_data = fake(QueueItemSchema % {"state": state})

    actual_mr_iid = mr_iid if mr_iid is not None else item_data["mr_iid"]
    actual_title = title if title is not None else item_data["title"]
    actual_author_name = author_name if author_name is not None else item_data["author_name"]
    actual_author_username = author_username if author_username is not None else item_data["author_username"]
    actual_target_branch = target_branch if target_branch is not None else item_data["target_branch"]
    actual_author_avatar = author_avatar if author_avatar is not None else item_data.get("author_avatar")

    item = QueueItem(
        mr_iid=actual_mr_iid,
        title=actual_title,
        author_name=actual_author_name,
        author_username=actual_author_username,
        author_avatar=actual_author_avatar,
        state=state,
        is_hotfix=is_hotfix,
        labels=labels or [Labels.MERGE_QUEUE],
        target_branch=actual_target_branch,
        queued_at=queued_at or datetime.now(UTC),
        started_at=started_at,
        finished_at=finished_at,
        pipeline_id=pipeline_id,
        pipeline_status=pipeline_status,
        last_error=last_error,
        retry_count=retry_count,
    )
    return item


# Alias for backward compatibility
create_test_queue_item = created_test_queue_item


def created_test_history_items(count: int = 5) -> list[QueueItem]:
    """Create a list of test history items.

    Uses d42 schemas to generate realistic random data for each item.

    Args:
        count: Number of items to create.

    Returns:
        List of QueueItem objects representing completed MRs.
    """
    items = []
    statuses = [QueueState.MERGED, QueueState.FAILED, QueueState.CONFLICT, QueueState.REMOVED]

    for i in range(count):
        status = statuses[i % len(statuses)]
        finished_at = datetime.now(UTC) - timedelta(hours=i)
        queued_at = finished_at - timedelta(minutes=30)
        started_at = queued_at + timedelta(minutes=5)

        items.append(
            created_test_queue_item(
                state=status,
                queued_at=queued_at,
                started_at=started_at,
                finished_at=finished_at,
                last_error=f"Test error for {status}" if status != QueueState.MERGED else None,
            )
        )

    return items


# Alias for backward compatibility
create_test_history_items = created_test_history_items


__all__ = [
    # Aliases for backward compatibility
    "create_expired_jwt",
    "create_invalid_jwt",
    "create_mock_circuit_breaker",
    "create_mock_database",
    "create_mock_gitlab_client",
    "create_mock_health",
    "create_mock_notifier",
    "create_mock_queue_manager",
    "create_mock_retry_manager",
    "create_mock_settings",
    "create_test_app",
    "create_test_app_with_db",
    "create_test_history_items",
    "create_test_jwt",
    "create_test_queue_item",
    "create_webhook_state",
    # New names (preferred)
    "created_expired_jwt",
    "created_invalid_jwt",
    "created_mock_circuit_breaker",
    "created_mock_database",
    "created_mock_gitlab_client",
    "created_mock_health",
    "created_mock_notifier",
    "created_mock_queue_manager",
    "created_mock_retry_manager",
    "created_mock_settings",
    "created_test_app",
    "created_test_app_with_db",
    "created_test_circuit_breaker",
    "created_test_history_items",
    "created_test_jwt",
    "created_test_queue_item",
    "created_webhook_state",
]
