from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from gitlab_queue.models.mr import MergeRequest, Note
    from gitlab_queue.models.pipeline import Job, Pipeline


@runtime_checkable
class GitLabClientProtocol(Protocol):
    async def get_mr(self, iid: int) -> MergeRequest: ...
    async def list_mrs_with_label(self, label: str, *, state: str = "opened") -> list[MergeRequest]: ...
    async def rebase_mr(self, iid: int) -> bool: ...
    async def check_rebase_status(self, iid: int) -> tuple[bool, bool]: ...
    async def get_mr_conflicts(self, iid: int) -> list[str]: ...
    async def merge_mr(self, iid: int, *, expected_sha: str | None = None) -> MergeRequest: ...
    async def remove_mr_label(self, iid: int, label: str) -> MergeRequest: ...

    async def get_mr_pipelines(self, iid: int) -> list[Pipeline]: ...
    async def get_latest_mr_pipeline(self, iid: int) -> Pipeline | None: ...
    async def get_pipeline_status(self, pipeline_id: int) -> Pipeline: ...
    async def retry_pipeline_job(self, job_id: int) -> Job: ...
    async def create_pipeline(self, ref: str) -> Pipeline: ...
    async def cancel_pipeline(self, pipeline_id: int) -> Pipeline: ...
    async def get_pipeline_jobs(self, pipeline_id: int) -> list[Job]: ...

    async def add_comment(self, iid: int, body: str) -> Note: ...
    async def update_comment(self, iid: int, note_id: int, body: str) -> Note: ...
    async def add_or_update_pinned_comment(self, iid: int, body: str) -> Note: ...

    async def get_project_web_url(self) -> str: ...


@runtime_checkable
class QueueManagerProtocol(Protocol):
    async def add_to_queue(self, mr: MergeRequest, is_hotfix: bool = False) -> Any: ...
    async def remove_from_queue(self, mr_iid: int) -> bool: ...
    async def get_queue_position(self, mr_iid: int) -> int | None: ...
    async def get_next_mr(self) -> Any | None: ...
    async def get_queue_item(self, mr_iid: int) -> Any | None: ...
    async def get_active_queue(self) -> list[Any]: ...
    async def get_queue_length(self) -> int: ...
    async def get_mr_state(self, mr_iid: int) -> dict[str, Any] | None: ...
    async def update_mr_state(self, mr_iid: int, state: str, **extra: Any) -> bool: ...
    async def update_hotfix_status(self, mr_iid: int, is_hotfix: bool, labels: list[str]) -> bool: ...
    async def complete_mr(
        self,
        mr_iid: int,
        status: str,
        failure_reason: str | None = None,
        pipeline_duration_seconds: int | None = None,
        pipeline_failed_jobs: list[str] | None = None,
    ) -> bool: ...
    async def get_queue_stats(self) -> dict[str, int]: ...
    async def get_stale_mrs(self, hours: int) -> list[Any]: ...
    async def mark_stale_warning_sent(self, mr_iid: int) -> bool: ...


@runtime_checkable
class NotifierProtocol(Protocol):
    async def notify(self, mr_iid: int, status: str, **context: Any) -> Note: ...
    async def build_pipeline_url(self, pipeline_id: int) -> str: ...
    async def remove_queue_label(self, mr_iid: int) -> None: ...


@runtime_checkable
class StateMachineProtocol(Protocol):
    @property
    def current_state(self) -> Any: ...

    async def trigger_start_processing(self) -> None: ...
    async def trigger_rebase_complete(
        self,
        *,
        pipeline_id: int,
        pipeline_url: str,
        expected_sha: str | None = None,
    ) -> None: ...
    async def trigger_rebase_failed(self, *, conflicted_files: list[str], error_message: str) -> None: ...
    async def trigger_conflict_during_testing(self, *, conflicted_files: list[str], error_message: str) -> None: ...
    async def trigger_pipeline_success(self) -> None: ...
    async def trigger_pipeline_failed(
        self, *, failed_jobs: list[str], retried_jobs: dict[str, int], error_message: str
    ) -> None: ...
    async def trigger_merge_success(self) -> None: ...
    async def trigger_merge_failed(self, *, error_message: str) -> None: ...
    async def trigger_mark_removed(self, *, reason: str = "label_removed") -> None: ...
    async def trigger_timeout(self, *, max_wait_hours: int = 2) -> None: ...

    async def notify_job_retry(
        self,
        *,
        pipeline_id: int,
        pipeline_url: str | None,
        retried_jobs: list[str],
        retried_counts: dict[str, int],
        max_retries: int,
    ) -> None: ...
    async def notify_position_changed(self, *, old_position: int) -> None: ...
    async def notify_rebase_complete(self) -> None: ...
    async def notify_stale_warning(self, *, warning_hours: int) -> None: ...
    async def notify_rebase_during_testing(
        self,
        *,
        old_pipeline_id: int | None,
        new_pipeline_id: int,
        rebase_count: int,
        max_attempts: int,
        expected_sha: str | None = None,
    ) -> None: ...


class StateMachineFactoryProtocol(Protocol):
    async def __call__(
        self,
        mr_iid: int,
        notifier: NotifierProtocol,
        queue_manager: QueueManagerProtocol,
        *,
        target_branch: str = "master",
        websocket_manager: Any | None = None,
        position_notifier: Any | None = None,
    ) -> StateMachineProtocol: ...
