"""initial schema

Revision ID: 34c99f29b96d
Revises:
Create Date: 2025-12-06 20:30:14.337376
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "34c99f29b96d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merge_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("iid", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("author_username", sa.Text(), nullable=False),
        sa.Column("author_avatar", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("is_hotfix", sa.Integer(), server_default="0", nullable=False),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("target_branch", sa.Text(), nullable=False),
        sa.Column("queued_at", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=True),
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("pipeline_status", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("stale_warning_sent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.Text(), server_default="CURRENT_TIMESTAMP", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iid"),
    )
    with op.batch_alter_table("merge_requests", schema=None) as batch_op:
        batch_op.create_index("idx_mr_finished_at", ["finished_at"], unique=False)
        batch_op.create_index("idx_mr_iid", ["iid"], unique=False)
        batch_op.create_index("idx_mr_queued_at", ["queued_at"], unique=False)
        batch_op.create_index("idx_mr_status", ["status"], unique=False)

    op.create_table(
        "webhook_dlq",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=False),
        sa.Column("original_created_at", sa.Text(), nullable=False),
        sa.Column("moved_to_dlq_at", sa.Text(), server_default="CURRENT_TIMESTAMP", nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_dlq", schema=None) as batch_op:
        batch_op.create_index("idx_dlq_event_type", ["event_type"], unique=False)
        batch_op.create_index("idx_dlq_moved_at", ["moved_to_dlq_at"], unique=False)

    op.create_table(
        "webhook_retry_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("next_attempt_at", sa.Text(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), server_default="CURRENT_TIMESTAMP", nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("webhook_retry_queue", schema=None) as batch_op:
        batch_op.create_index("idx_retry_event_type", ["event_type"], unique=False)
        batch_op.create_index("idx_retry_next_attempt", ["next_attempt_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_retry_queue", schema=None) as batch_op:
        batch_op.drop_index("idx_retry_next_attempt")
        batch_op.drop_index("idx_retry_event_type")

    op.drop_table("webhook_retry_queue")
    with op.batch_alter_table("webhook_dlq", schema=None) as batch_op:
        batch_op.drop_index("idx_dlq_moved_at")
        batch_op.drop_index("idx_dlq_event_type")

    op.drop_table("webhook_dlq")
    with op.batch_alter_table("merge_requests", schema=None) as batch_op:
        batch_op.drop_index("idx_mr_status")
        batch_op.drop_index("idx_mr_queued_at")
        batch_op.drop_index("idx_mr_iid")
        batch_op.drop_index("idx_mr_finished_at")

    op.drop_table("merge_requests")
    # ### end Alembic commands ###
