"""add_history_and_analytics_tables

Revision ID: a312c27ba5f7
Revises: 34c99f29b96d
Create Date: 2025-12-06 20:37:29.094857
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a312c27ba5f7"
down_revision: str | None = "34c99f29b96d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Text(), nullable=False),
        sa.Column("total_processed", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("timeout_count", sa.Integer(), nullable=False),
        sa.Column("hotfix_count", sa.Integer(), nullable=False),
        sa.Column("avg_wait_time_seconds", sa.Integer(), nullable=True),
        sa.Column("avg_processing_time_seconds", sa.Integer(), nullable=True),
        sa.Column("max_queue_depth", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    with op.batch_alter_table("analytics_daily", schema=None) as batch_op:
        batch_op.create_index("idx_daily_date", ["date"], unique=False)

    op.create_table(
        "analytics_hourly",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.Text(), nullable=False),
        sa.Column("queue_depth", sa.Integer(), nullable=False),
        sa.Column("processed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("avg_wait_time_seconds", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analytics_hourly", schema=None) as batch_op:
        batch_op.create_index("idx_hourly_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "merge_requests_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("iid", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("author_username", sa.Text(), nullable=False),
        sa.Column("author_avatar", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_hotfix", sa.Integer(), server_default="0", nullable=False),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("target_branch", sa.Text(), nullable=False),
        sa.Column("queued_at", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.Text(), nullable=False),
        sa.Column("wait_time_seconds", sa.Integer(), nullable=True),
        sa.Column("processing_time_seconds", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("pipeline_status", sa.Text(), nullable=True),
        sa.Column("pipeline_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("pipeline_failed_jobs", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), server_default="CURRENT_TIMESTAMP", nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("merge_requests_history", schema=None) as batch_op:
        batch_op.create_index("idx_history_finished_at", ["finished_at"], unique=False)
        batch_op.create_index("idx_history_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merge_requests_history", schema=None) as batch_op:
        batch_op.drop_index("idx_history_status")
        batch_op.drop_index("idx_history_finished_at")

    op.drop_table("merge_requests_history")
    with op.batch_alter_table("analytics_hourly", schema=None) as batch_op:
        batch_op.drop_index("idx_hourly_timestamp")

    op.drop_table("analytics_hourly")
    with op.batch_alter_table("analytics_daily", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_date")

    op.drop_table("analytics_daily")
    # ### end Alembic commands ###
